// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rkwapcbzgcjzpizhzhtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrd2FwY2J6Z2NqenBpemh6aHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NDQ3MDksImV4cCI6MjA4ODIyMDcwOX0.t7oBDye9iYoJEU6UBjXHN9Q_Tnk2p0suyTzx6Phkugc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});